h0 = figure('menubar','none',...                                %创建窗口
    'position',[198 56 450 500],...
    'name','3D图形的色彩配置');
h1 = axes('parent',h0,...                                       %创建坐标轴
    'position',[0.15 0.45 0.7 0.5],...
    'visible','off');
z = peaks(25); 
surf(z);                                                        %创建三维图形
c = [0.8 0.1 0.1];
colormap(c)                                                     %图形色彩
ifv = c;
set(0,'defaultuicontrolbackgroundcolor',get(h0,'Color'))        %设置默认控件背景色
p1 = uicontrol('parent',h0,...                                  %创建【重置】按钮
    'style','pushbutton',...
    'string','重置',...
    'position',[330 120 50 30],...
    'callback',[...
        'set(s1,''value'',ifv(1));,',...
        'set(s2,''value'',ifv(2));,',...
        'set(s3,''value'',ifv(3));,',...
        'set(t1,''string'',sprintf(''红色成分：%3.2f'',ifv(1)));',...
        'set(t2,''string'',sprintf(''绿色成分：%3.2f'',ifv(2)));',...
        'set(t3,''string'',sprintf(''蓝色成分：%3.2f'',ifv(2)));',...
        'set(h0,''colormap'',ifv)']);
p2 = uicontrol('parent',h0,...                                  %创建【关闭】按钮
    'style','pushbutton',...
    'string','关闭',...
    'position',[330 60 50 30],...
    'callback','closereq');
t1 = uicontrol('parent',h0,...                                  %创建【红色成分】按钮
    'style','text',...
    'string','红色成分：1.00',...
    'position',[100 170 120 20]);
t2 = uicontrol('parent',h0,...                                  %创建【绿色成分】按钮
    'style','text',...
    'string','绿色成分：0.00',...
    'position',[100 120 120 20]);
t3 = uicontrol('parent',h0,...                                  %创建【蓝色成分】按钮
    'style','text',...
    'string','蓝色成分：0.00',...
    'position',[100 70 120 20]); 
s1 = uicontrol('parent',h0,...                                  %创建【红色成分滑动条】
    'style','slider',...
    'value',c(1),...
    'position',[100 150 200 20],...
    'callback',[...
        'v1=get(s1,''value'');,',...
        'c(1)=v1;,',...
        'set(h0,''colormap'',c);',...
        'set(t1,''string'',sprintf(''红色成分：%3.2f'',c(1)));']);
s2 = uicontrol('parent',h0,...                                  %创建【绿色成分滑动条】
    'style','slider',...
    'value',c(2),...
    'position',[100 100 200 20],...
    'callback',[...
        's2k=get(s2,''value'');,',...
        'c(2)=s2k;,',...
        'set(h0,''colormap'',c);',...
        'set(t2,''string'',sprintf(''绿色成分：%3.2f'',c(2)));']);
s3 = uicontrol('parent',h0,...                                  %创建【蓝色成分滑动条】
    'style','slider',...
    'value',c(3),...
    'position',[100 50 200 20],...
    'callback',[...
        's3k=get(s3,''value'');,',...
        'c(3)=s3k;,',...
        'set(h0,''colormap'',c);',...
        'set(t3,''string'',sprintf(''蓝色成分：%3.2f'',c(3)));']);
