fig = figure('menubar', 'none');                        %创建窗口，并隐藏菜单栏和工具栏
h = uimenu(fig, 'label', '&Tool', 'Accelerator', 'T');  %创建菜单并设置快捷键
h1 = uimenu(h, 'tag', 'g_on', 'label', 'grid on', 'Callback',...
    ['set(h1,''checked'',''on'');',...                  %创建菜单选项【grid on】
    'set(h2,''checked'',''off'');',...
    'grid on']);
h2 = uimenu(h, 'label', 'grid off', 'checked', 'on', 'Callback',...
    ['set(h2,''checked'',''on'');',...                  %创建菜单选项【grid off】
    'set(h1,''checked'',''off'');',...
    'grid off']);
