h0 = figure('menubar', 'none', ...
    'NumberTitle', 'off', ...
    'position', [200 150 300 150], ...
    'name', '简易时钟');   %创建窗口
set(0, 'DefaultUicontrolBackgroundColor', get(h0, 'color')) %设置控件默认背景色
set(0, 'DefaultUicontrolUnits', 'points')                   %设置控件默认字体单位
set(0, 'DefaultUicontrolFontsize', 12)                      %设置控件默认字体大小
now = floor(clock);                                         %获取当前时刻
e1 = uicontrol('parent', h0, ...                            %创建方框显示年份数据
    'enable', 'inactive', ...
    'BackgroundColor', 'w', ...
    'style', 'edit', ...
    'horizontal', 'right', ...
    'position', [20 80 30 20], ...
    'string', num2str(now(1)));
t1 = uicontrol('parent', h0, ...                            %显示【年】
    'style', 'text', ...
    'string', '年', ...
    'fontsize', 14, ...
    'position', [55 80 20 20]);
e2 = uicontrol('parent', h0, ...                            %创建方框显示月份数据
    'enable', 'inactive', ...
    'BackgroundColor', 'w', ...
    'style', 'edit', ...
    'horizontal', 'right', ...
    'position', [80 80 30 20], ...
    'string', num2str(now(2)));
t2 = uicontrol('parent', h0, ...                            %显示【月】
    'style', 'text', ...
    'string', '月', ...
    'fontsize', 14, ...
    'position', [115 80 20 20]);
e3 = uicontrol('parent', h0, ...                            %创建方框显示日份数据
    'enable', 'inactive', ...
    'BackgroundColor', 'w', ...
    'style', 'edit', ...
    'horizontal', 'right', ...
    'position', [140 80 30 20], ...
    'string', num2str(now(3)));
t3 = uicontrol('parent', h0, ...                            %显示【日】
    'units', 'points', ...
    'tag', 't3', ...
    'style', 'text', ...
    'string', '日', ...
    'fontsize', 14, ...
    'position', [175 80 20 20]);
e4 = uicontrol('parent', h0, ...                            %显示时、分、秒
    'enable', 'inactive', ...
    'BackgroundColor', 'w', ...
    'style', 'edit', ...
    'horizontal', 'right', ...
    'position', [40 30 80 20], ...
    'string', [num2str(now(4)) '：' num2str(now(5)) '：' num2str(now(6))]);
b1=uicontrol('parent',h0,...                                %显示【关闭】按钮
    'string','关闭',...
    'position',[150 30 50 20],...
    'callback',[...
        'k=1;,',...
        'close']);
k=0;                                                        %循环标志
while ishandle(h0)                                          %时间刷新
    now1 = floor(clock);
    set(e1, 'string', num2str(now1(1)));
    set(e2, 'string', num2str(now1(2)));
    set(e3, 'string', num2str(now1(3)));
    set(e4, 'string', [num2str(now1(4)) '：' num2str(now1(5)) '：' num2str(now1(6))]);
    pause(1)                                                %循环周期
    if k == 1                                               %跳出循环
        break
    end
end
