h0 = figure('menubar', 'none', 'NumberTitle', 'off', ...
    'position', [198 56 350 400], ...
    'name', '控制运动小球的角速度');
h1 = axes('parent', h0, ...
    'position', [0.25 0.45 0.5 0.5], ...
    'visible', 'off');
t = 0 : 0.1 : 4 * pi;
x = sin(t);
y = cos(t);
line(x, y);
axis equal
axis off
set(0, 'DefaultUicontrolBackgroundColor', get(h0, 'color'))
set(0, 'DefaultUicontrolFontsize', 12) 
h = line('xdata', 0, ...
    'ydata', 1, ...
    'marker', 'o', ...
    'MarkerFaceColor', 'r', ...
    'markersize', 15, ...
    'erasemode', 'xor');
n = length(t);
i = 1;
speed = 0.01;
k = 0;
b1_Callback = ['k=0;',...
        'while 1,',...
        'set(h,''xdata'',x(i),''ydata'',y(i));',...
        'drawnow,',...
        'pause(speed),',...
        'i=i+1;,',...
        'if i>n,',...
        'i=1;',...
        'end,',...
        'if k==1,',...
        'break,',...
        'end,',...
        'end'];
b1=uicontrol('parent',h0,...
    'units','points',...
    'tag','b1',...
    'style','pushbutton',...
    'string','开始',...
    'position',[30 50 50 20],...
    'callback',b1_Callback);
b2=uicontrol('parent',h0,...
    'units','points',...
    'tag','b2',...
    'style','pushbutton',...
    'string','停止',...
    'position',[100 50 50 20],...
    'callback','k=1;');
b3=uicontrol('parent',h0,...
    'units','points',...
    'tag','b3',...
    'style','pushbutton',...
    'string','反向',...
    'position',[170 50 50 20],...
    'callback',[...
        'temp=x;,',...
        'x=y;',...
        'y=temp;']);
b4=uicontrol('parent',h0,...
    'units','points',...
    'tag','b3',...
    'style','pushbutton',...
    'string','关闭',...
    'position',[100 20 50 20],...
    'callback',[...
        'k=1;,',...
        'closereq']);
s1=uicontrol('style','slider',...
    'parent',h0,...
    'units','points',...
    'tag','s1',...
    'value',50*speed,...
    'position',[40 90 190 15],...
    'callback',[...
        'm=get(s1,''value'');,',...
        'speed=m/50;']);
t1=uicontrol('parent',h0,...
    'units','points',...
    'tag','t1',...
    'style','text',...
    'fontsize',12,...
    'string','小球运动速度',...
'position',[40 110 190 20]);
