h = figure('menubar', 'none', 'NumberTitle', 'off', 'Units', 'pixels', ...
    'name', '文件浏览器', 'position', [200 200 250 300]);   %创建窗口
set(0, 'defaultuicontrolfontsize', 10)                     %设置默认控件字体大小
h1 = uicontrol('Units', 'pixels', 'position', [20 260 70 30], 'string', '选择路径', 'callback', ...
    ['str = uigetdir(''C:\Documents and Settings\Administrator\桌面'', ''选择目录'');',...
    'if str,',...
    'set(h2, ''string'', str),',...
    'str_all = dir([str ''\*.m'']);',...
    'set(h3, ''string'', {str_all.name}),',...
    'end']);                                               %创建【选择路径】按钮
h2 = uicontrol('style', 'edit', 'Units', 'pixels', 'position', ...
    [100 262 130 25], 'horizontal', 'left', 'string', ''); %显示所选路径
h3 = uicontrol('style', 'listbox', 'Units', 'pixels', ...
    'position', [20 20 210 230], 'string', '');            %创建m文件列表框
